@startuml
'https://plantuml.com/class-diagram


' Configuración para que las líneas sean rectas
skinparam Linetype ortho

entity "Agencia" {
    * Agencia_Nro_Agencia: bigint <<PK>>
    --
    * ubicacion_cod: bigint <<FK>>
    * Agencia_direccion: nvarchar (255)
    * Agencia_Telefono: nvarchar (255)
    * Agencia_Mail: nvarchar (255)
}


entity "Agente" {
    * Agente_Legajo: bigint<<PK>>
    --
    * Ubicacion : bigint <<FK>>
	* Agente_Nombre nvarchar(255)
	* Agente_Apellido nvarchar(255)
	* Agente_Dni: nvarchar(255)
	* Agente_Fecha_Nac: date
	* Agente_Telefono: nvarchar(255)
	* Agente_Mail: nvarchar(255)
	* Agente_Direccion: nvarchar(255)
}

entity Cliente {
    * cliente_cod: bigint <<PK>>
    --
    * Ubicacion_cod: bigint <<FK>>
    * Cliente_Nombre: nvarchar (255)
	* Cliente_Apellido: nvarchar (255)
	* Cliente_Dni: nvarchar(255)
	* Cliente_Tel: nvarchar(255)
	* Cliente_Mail: nvarchar(255)
	* Cliente_Direccion: nvarchar(255)
	* Cliente_Fecha_Nac: date

}

entity "Ubicacion" {
    * Ubicacion_cod: bigint <<PK>>
    --
    * Ubicacion_Localidad: nvarchar (255)
    * Ubicacion_Provincia: nvarchar (255)
}

entity "Venta" {
    * Venta_Nro_Venta : bigint <<PK>>
    --
    * Agencia_Nro_Agencia : bigint <<FK>>
    * Nro_cliente : bigint <<FK>>
    * Agente_Legajo : bigint <<FK>>
    * Venta_Fecha_Venta: date
    * Venta_Canal_Venta : String <<FK>>
    * Propuesta_Nro_Propuesta : bigint <<FK>>
    * Venta_Subtotal: decimal(18, 2)
    * Venta_Descuento : decimal(18, 2)
    * Venta_Importe_Total : decimal(18, 2)
    * Venta_Medio_Pago: nvarchar(255)
}


entity "Hospedaje"{
    * Hospedaje_Codigo : nvarchar(255) <<PK>>
    --
    * Hospedaje_Ciudad : nvarchar(255)
    * Hospedaje_Pais : nvarchar(255)
    * Hospedaje_Nombre : nvarchar(255)
    * Hospedaje_Direccion : nvarchar(255)
    * Hospedaje_Incluye_Desayuno : bit
    * Hospedaje_Check_In : nvarchar(50)
    * Hospedaje_Check_Out : nvarchar(50)
}
entity Detalle_Venta_Hospedaje {
    * Detalle_Venta_Hospedaje : int <<PK>>
    * Venta_Nro_Venta : bigint <<PK>>
    --
    * Detalle_Venta_Hospedaje_Precio_Unitario: decimal(18, 2)
    * Detalle_Venta_Hospedaje_Subtotal: decimal(18, 2)
    * Detalle_Venta_Hospedaje_Cod_Reserva: nvarchar(255)
}

entity "Habitacion" {
    * Habitacion_Codigo : nvarchar(50) <<PK>>
    --
    * Hospedaje_Codigo : nvarchar(255) <<FK>>
    * Habitacion_Nombre: nvarchar(255)
    * Habitacion_Descripcion: nvarchar(max)
    * Habitacion_Precio_Noche: decimal(18, 2)
}

entity "Excursion"{
    * Excursion_Codigo : nvarchar(255) <<PK>>
    --
    * Excursion_Nombre : nvarchar(255)
    * Excursion_Descripcion : nvarchar(max)
    * Excursion_Horario : nvarchar(50)
    * Excursion_Duracion : int
    * Excursion_Precio : decimal(18, 2)
}

entity Detalle_Venta_Excursion {
    * Excursion_Codigo: nvarchar(255) <<PK>>
    * Venta_Nro_Venta : bigint <<PK>>
    --
    *Detalle_Venta_Excursion_Fecha_Reserva: date
    *Detalle_Venta_Excursion_Cant: int
    *Detalle_Venta_Excursion_Precio_Unitario: decimal(18, 2)
    *Detalle_Venta_Excursion_Subtotal: decimal(18, 2)
    *Detalle_Venta_Excursion_Cod_Reserva: nvarchar(255)
}

entity "Vuelo"{
    * Vuelo_Codigo: bigint <<PK>>
    --
    * Aerolinea_Codigo : nvarchar(255) <<FK>>
    * Aeropuerto_Salida_Codigo : nvarchar(10) <<FK>>
    * Aeropuerto_Llegada_Codigo : nvarchar(10) <<FK>>
    * Vuelo_Fecha_Salida : date
    * Vuelo_Hora_Salida : nvarchar(50)
    * Vuelo_Fecha_Llegada : date
    * Vuelo_Hora_Llegada : nvarchar(50)
    * Vuelo_Duracion : int
    * Vuelo_Precio: decimal(18,2)
    * Vuelo_Incluye_Carry : bit
    * Vuelo_Incluye_Valija : bit

}

entity Detalle_Venta_Vuelo{
	* Detalle_Venta_Vuelo_Cod_Reserva : nvarchar(255) <<PK>>
	* Venta_Nro_Venta : bigint <<PK>>
	--
    * Detalle_Venta_Vuelo_Cantidad_Pasajes : int
	* Detalle_Venta_Vuelo_Precio_Unitario : decimal(18, 2)
	* Detalle_Venta_Vuelo_Subtotal : decimal(18, 2)
}

entity SolicitudCotizacion {
    * Solicitud_Nro_Solicitud bigint <<PK>>
     --
    * Solicitud_cod_cliente : bignit <<FK>>
    * Solicitud_Fecha_Solicitud : date
    * Solicitud_Fecha_Inicio_Tentativa : date
    * Solicitud_Fecha_Fin_Tentativa : date
    * Solicitud_Cant_Pax : int
    * Solicitud_Presupuesto_Estimado : decimal(18, 2)
    * Solicitud_Agente : bigint <<FK>>

}

entity DetalleCiudad{
    * Detalle_Solicitud_cod_Ciudad : nvarchar(255) <<PK>>
     --
    * Detalle_Solicitud_Cant_Dias_Aprox : int
    * Detalle_Solicitud_Ciudad : nvarchar(255)
    * Detalle_Solicitud_Observaciones : nvarchar(max)
    * Detalle_Nro_Solicitud : bigint <<FK>>
}


entity Propuesta {
    * Propuesta_Nro_Propuesta : bigint <<PK>>
     --
    * Propuesta_Solicitud : bigint <<FK>>
    * Propuesta_Agente : bigint <<FK>>
    * Propuesta_Fecha_Emision : date
    * Propuesta_Vigencia_Hasta : date
    * Propuesta_Fecha_Desde : date
    * Propuesta_Fecha_Hasta : date
    * Propuesta_Subtotal : decimal(18, 2)
    * Propuesta_Descuento : decimal(18, 2)
    * Propuesta_Importe_Total : decimal(18, 2)
    * Propuesta_Estado : nvarchar(255)

}

entity DetallePropuestaVuelo {
     * Detalle_Propuesta_Cod : bigint <<PK>>
      --
     * Detalle_Propuesta_Vuelo_Cod_Vuelo: bigint <<FK>>
     * Detalle_Propuesta_Cod_Propuesta : bigint <<FK>>
     * Detalle_Propuesta_Vuelo_Cant_Pasajes : int
     * Detalle_Propuesta_Vuelo_Precio : decimal(18, 2)
     * Detalle_Propuesta_Vuelo_Subtotal decimal(18, 2)
}

entity DetallePropuestaHospedaje{
     * Detalle_Propuesta_Hospedaje_Cod : nvarchar(255) <<PK>>
     --
     * Detalle_Propuesta_Cod_Propuesta : bigint <<FK>>
     * Detalle_Propuesta_Hospedaje_Cod_Hospedaje: nvarchar(255) <<FK>>
     * Detalle_Propuesta_Hospedaje_Fecha_Desde: date
     * Detalle_Propuesta_Hospedaje_Fecha_Hasta: date
     * Detalle_Propuesta_Hospedaje_Cant: int
     * Detalle_Propuesta_Hospedaje_Precio: decimal(18, 2)
     * Detalle_Propuesta_Hospedaje_Subtotal: decimal(18, 2)
}

entity "Aerolinea" {
    * Aerolinea_Codigo : nvarchar(255) <<PK>>
    --
    * Aerolinea_Nombre : nvarchar(255)
    * Aerolinea_Pais : nvarchar(255)
    * Aerolinea_Alianza : nvarchar(255)
}

entity "Aeropuerto" {
    * Areopuerto_codigo : nvarchar(10) <<PK>>
    --
    * Aeropuerto_Descripcion : nvarchar(200)
    * Aeropuerto_Ciudad : nvarchar(200)
    * Aeropuerto_Pais : nvarchar(200)
}

entity "Encuesta" {
    * Encuesta_Codigo : bigint <<PK>>
    --
    * cliente_cod: bigint <<FK>>
    * Agente_Legajo: bigint <<FK>>
    * Venta_Nro_Venta : bigint <<FK>>
    * Propuesta_Nro_Propuesta : bigint <<FK>>
    * comentario : nvarchar(max)
}

entity CalificacionPorEncuesta {
    * Encuesta_Codigo : bigint <<FK>>
    * Aspecto_Codigo: bigint<<FK>>
    --
    * Aspecto_calificacion : int
}

entity "Aspecto" {
     * Aspecto_Codigo : bigint <<PK>>
     --
     * descripcion : nvarchar (255)
}




'RELACIONES
Agente }|--o| "Venta"
Agencia ||--o{ "Venta"
Agente }o--|| "Agencia"
Cliente ||--o{Venta
Vuelo }o--|| Aerolinea
Aeropuerto ||--o{ Vuelo : "Salida"
Aeropuerto ||--o{ Vuelo : "Llegada"
Detalle_Venta_Vuelo }|--|| Venta
Detalle_Venta_Vuelo }|--o| Vuelo
Hospedaje |o--|{ Detalle_Venta_Hospedaje
Detalle_Venta_Hospedaje }|--||Venta
Hospedaje||--|{Habitacion
Excursion }o--o{  Venta
Excursion |o--|{Detalle_Venta_Excursion
Detalle_Venta_Excursion }|--||Venta


Ubicacion ||--o{ Agencia
Ubicacion ||--o{ Agente

Aspecto |o--|{CalificacionPorEncuesta
CalificacionPorEncuesta}|--||Encuesta

Encuesta|o--||Venta

Cliente||--o{SolicitudCotizacion
SolicitudCotizacion}o--||Agente

SolicitudCotizacion|o--|{DetalleCiudad
SolicitudCotizacion||--o{Propuesta

Propuesta|o--||Agente
Propuesta||--o{DetallePropuestaVuelo
Propuesta||--o{DetallePropuestaHospedaje

DetallePropuestaVuelo|o--||Vuelo
DetallePropuestaHospedaje|o--||Hospedaje

Propuesta}o--o|Venta




@enduml