@startuml
'https://plantuml.com/class-diagram

' Configuración para que las líneas sean rectas
skinparam Linetype ortho


entity "Agencia" {
    * agencia_id: bigint <<PK>>
    --
    * agencia_localidad: bigint <<FK>>
    * agencia_direccion: nvarchar(255)
    * agencia_telefono: nvarchar(255)
    * agencia_mail: nvarchar(255)
}

entity "Agente" {
    * agente_legajo: bigint <<PK>>
    --
    * agente_agencia: bigint <<FK>>
    * agente_localidad: bigint <<FK>>
    * agente_nombre: nvarchar(255)
    * agente_apellido: nvarchar(255)
    * agente_dni: nvarchar(255)
    * agente_fecha_nac: date
    * agente_telefono: nvarchar(255)
    * agente_mail: nvarchar(255)
    * agente_direccion: nvarchar(255)
}

entity "Cliente" {
    * cliente_id: bigint <<PK>>
    --
    * cliente_localidad: bigint <<FK>>
    * cliente_nombre: nvarchar(255)
    * cliente_apellido: nvarchar(255)
    * cliente_dni: nvarchar(255)
    * cliente_telefono: nvarchar(255)
    * cliente_mail: nvarchar(255)
    * cliente_direccion: nvarchar(255)
    * cliente_fecha_nac: date
}

entity "Provincia" {
    * provincia_id: bigint <<PK>>
    --
    * provincia_nombre: nvarchar(255)
}

entity "Localidad" {
    * localidad_id: bigint <<PK>>
    --
    * localidad_provincia: bigint <<FK>>
    * localidad_nombre: nvarchar(255)
}

entity "Venta" {
    * venta_id: bigint <<PK>>
    --
    * venta_agencia: bigint <<FK>>
    * venta_cliente: bigint <<FK>>
    * venta_agente: bigint <<FK>>
    * venta_canal: bigint <<FK>>
    * venta_medio_pago: bigint <<FK>>
    * venta_fecha: date
    * venta_subtotal: decimal(18,2)
    * venta_descuento: decimal(18,2)
    * venta_importe_total: decimal(18,2)
}

entity "Venta_Propuesta" {
    * venta_prop_venta: bigint <<FK>>
    * venta_prop_propuesta: bigint <<FK>>
}

entity "Hospedaje" {
    * hospedaje_id: bigint <<PK>>
    --
    * hospedaje_ciudad: bigint <<FK>>
    * hospedaje_pais: bigint <<FK>>
    * hospedaje_nombre: nvarchar(255)
    * hospedaje_direccion: nvarchar(255)
    * hospedaje_incluye_desayuno: bit
    * hospedaje_check_in: nvarchar(50)
    * hospedaje_check_out: nvarchar(50)
}

entity "Detalle_Venta_Hospedaje" {
    * det_vta_hosp_venta: bigint <<FK>>
    * det_vta_hosp_habitacion: bigint <<FK>>
    * det_vta_hosp_hospedaje: bigint <<FK>>
    --
    * det_vta_hosp_fecha_desde: date
    * det_vta_hosp_fecha_hasta: date
    * det_vta_hosp_cantidad: int
    * det_vta_hosp_precio_unitario: decimal(18,2)
    * det_vta_hosp_subtotal: decimal(18,2)
    * det_vta_hosp_cod_reserva: nvarchar(255)
}

entity "Habitacion" {
    * habitacion_id: bigint <<PK>>
    --
    * habitacion_hospedaje: bigint <<FK>>
    * habitacion_nombre: nvarchar(255)
    * habitacion_descripcion: nvarchar(max)
    * habitacion_precio_noche: decimal(18,2)
}

entity "Excursion" {
    * excursion_id: bigint <<PK>>
    --
    * excursion_proveedor: bigint <<FK>>
    * excursion_nombre: nvarchar(255)
    * excursion_descripcion: nvarchar(max)
    * excursion_horario: nvarchar(50)
    * excursion_duracion: int
    * excursion_precio: decimal(18,2)
}

entity "Proveedor" {
    * proveedor_id: bigint <<PK>>
    --
    * proveedor_nombre: nvarchar(255)
    * proveedor_mail: nvarchar(255)
    * proveedor_telefono: nvarchar(255)
}

entity "Detalle_Venta_Excursion" {
    * det_vta_excur_excursion: bigint <<FK>>
    * det_vta_excur_venta: bigint <<FK>>
    --
    * det_vta_excur_fecha_reserva: date
    * det_vta_excur_cantidad: int
    * det_vta_excur_precio_unitario: decimal(18,2)
    * det_vta_excur_subtotal: decimal(18,2)
    * det_vta_excur_cod_reserva: nvarchar(255)
}

entity "Vuelo" {
    * vuelo_id: bigint <<PK>>
    --
    * vuelo_aerolinea: nvarchar(255) <<FK>>
    * vuelo_apto_salida: nvarchar(10) <<FK>>
    * vuelo_apto_llegada: nvarchar(10) <<FK>>
    * vuelo_fecha_salida: date
    * vuelo_hora_salida: nvarchar(50)
    * vuelo_fecha_llegada: date
    * vuelo_hora_llegada: nvarchar(50)
    * vuelo_duracion: int
    * vuelo_precio: decimal(18,2)
    * vuelo_incluye_carry: bit
    * vuelo_incluye_valija: bit
}

entity "Detalle_Venta_Vuelo" {
    * det_vta_vuelo_venta: bigint <<FK>>
    * det_vta_vuelo_vuelo: bigint <<FK>>
    --
    * det_vta_vuelo_cantidad: int
    * det_vta_vuelo_precio_unitario: decimal(18,2)
    * det_vta_vuelo_subtotal: decimal(18,2)
    * det_vta_vuelo_cod_reserva: nvarchar(255)
}

entity "SolicitudCotizacion" {
    * solicitud_id: bigint <<PK>>
    --
    * solicitud_cliente: bigint <<FK>>
    * solicitud_agente: bigint <<FK>>
    * solicitud_fecha: date
    * solicitud_fecha_inicio: date
    * solicitud_fecha_fin: date
    * solicitud_cant_pax: int
    * solicitud_observaciones: nvarchar(max)
    * solicitud_presupuesto: decimal(18,2)
}

entity "DetalleCiudad" {
    * det_ciudad_id: bigint <<PK>>
    --
    * det_ciudad_ciudad: bigint <<FK>>
    * det_ciudad_solicitud: bigint <<FK>>
    * det_ciudad_cant_dias: int
    * det_ciudad_observaciones: nvarchar(max)
}

entity "Propuesta" {
    * propuesta_id: bigint <<PK>>
    --
    * propuesta_solicitud: bigint <<FK>>
    * propuesta_agente: bigint <<FK>>
    * propuesta_estado: bigint <<FK>>
    * propuesta_fecha_emision: date
    * propuesta_vigencia: date
    * propuesta_fecha_desde: date
    * propuesta_fecha_hasta: date
    * propuesta_subtotal: decimal(18,2)
    * propuesta_descuento: decimal(18,2)
    * propuesta_importe_total: decimal(18,2)
}

entity "Estado" {
    * estado_id: bigint <<PK>>
    --
    * estado_nombre: nvarchar(255)
}

entity "DetallePropuestaVuelo" {
    * det_prop_vuelo_id: bigint <<PK>>
    --
    * det_prop_vuelo_vuelo: bigint <<FK>>
    * det_prop_vuelo_propuesta: bigint <<FK>>
    * det_prop_vuelo_cantidad: int
    * det_prop_vuelo_precio_unitario: decimal(18,2)
    * det_prop_vuelo_subtotal: decimal(18,2)
}

entity "DetallePropuestaHospedaje" {
    * det_prop_hosp_id: bigint <<PK>>
    --
    * det_prop_hosp_propuesta: bigint <<FK>>
    * det_prop_hosp_hospedaje: bigint <<FK>>
    * det_prop_hosp_fecha_desde: date
    * det_prop_hosp_fecha_hasta: date
    * det_prop_hosp_cantidad: int
    * det_prop_hosp_precio_unitario: decimal(18,2)
    * det_prop_hosp_subtotal: decimal(18,2)
}

entity "Aerolinea" {
    * aerolinea_codigo: nvarchar(255) <<PK>>
    --
    * aerolinea_pais: bigint <<FK>>
    * aerolinea_alianza: bigint <<FK>>
    * aerolinea_nombre: nvarchar(255)
}

entity "Alianza" {
    * alianza_id: bigint <<PK>>
    --
    * alianza_nombre: nvarchar(255)
}

entity "Aeropuerto" {
    * aeropuerto_codigo: nvarchar(10) <<PK>>
    --
    * aeropuerto_descripcion: nvarchar(200)
    * aeropuerto_ciudad: bigint <<FK>>
}

entity "Encuesta" {
    * encuesta_id: bigint <<PK>>
    --
    * encuesta_cliente: bigint <<FK>>
    * encuesta_agente: bigint <<FK>>
    * encuesta_venta: bigint <<FK>>
    * encuesta_propuesta: bigint <<FK>>
    * encuesta_fecha: date
    * encuesta_comentarios: nvarchar(max)
}

entity "CalificacionPorEncuesta" {
    * calificacion_encuesta: bigint <<FK>>
    * calificacion_aspecto: bigint <<FK>>
    --
    * calificacion_valor: int
}

entity "Aspecto" {
    * aspecto_id: bigint <<PK>>
    --
    * aspecto_descripcion: nvarchar(255)
}

entity "Medio_Pago" {
    * medio_pago_id: bigint <<PK>>
    --
    * medio_pago_detalle: nvarchar(255)
}

entity "Canal_Venta" {
    * canal_id: bigint <<PK>>
    --
    * canal_detalle: nvarchar(255)
}

entity "Pais" {
    * pais_id: bigint <<PK>>
    --
    * pais_nombre: nvarchar(255)
}

entity "Ciudad" {
    * ciudad_id: bigint <<PK>>
    --
    * ciudad_pais: bigint <<FK>>
    * ciudad_nombre: nvarchar(255)
}


'RELACIONES
Agente }|--o| "Venta"
Agencia ||--o{ "Venta"
Agente }o--|| "Agencia"
Cliente ||--o{Venta
Vuelo }o--|| Aerolinea
Aeropuerto ||--o{ Vuelo : "Salida"
Aeropuerto ||--o{ Vuelo : "Llegada"
Detalle_Venta_Vuelo }|--|| Venta
Detalle_Venta_Vuelo }|--o| Vuelo
Hospedaje |o--|{ Detalle_Venta_Hospedaje
Detalle_Venta_Hospedaje }|--||Venta
Hospedaje||--|{Habitacion
Excursion }o--|| Proveedor
Excursion |o--|{Detalle_Venta_Excursion
Detalle_Venta_Excursion }|--||Venta

Provincia ||--|{ Localidad
Localidad ||--o{ Agencia
Localidad ||--o{ Agente
Localidad ||--o{ Cliente

Aspecto |o--|{CalificacionPorEncuesta
CalificacionPorEncuesta}|--||Encuesta

Encuesta|o--o|Venta
Encuesta|o--o|Propuesta

Cliente||--o{SolicitudCotizacion
SolicitudCotizacion}o--||Agente

SolicitudCotizacion|o--|{DetalleCiudad
SolicitudCotizacion||--o{Propuesta

Propuesta|o--||Agente
Propuesta||--o{DetallePropuestaVuelo
Propuesta||--o{DetallePropuestaHospedaje
Propuesta}|--||Estado
Venta ||--o| Venta_Propuesta
Propuesta ||--o|Venta_Propuesta

DetallePropuestaVuelo|o--||Vuelo
DetallePropuestaHospedaje|o--||Hospedaje

Canal_Venta ||--o{ Venta
Medio_Pago ||--o{ Venta

Pais ||--|{Ciudad
Ciudad ||--o{ Hospedaje
Aeropuerto }o--|| Ciudad
Aerolinea }o--|| Pais
Ciudad ||--o{ DetalleCiudad

Alianza ||--|{ Aerolinea

@enduml
